import { PatientProfile, TrialEvaluation } from "../types";

export function generateMarkdownExport(
  patient: PatientProfile,
  evaluations: TrialEvaluation[]
): string {
  const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  
  let md = `# Clinical Trial Eligibility Matcher - Adjudication Report\n\n`;
  md += `**Date:** ${dateStr}  \n`;
  md += `**Patient Identifier:** ${patient.id} (${patient.name})  \n`;
  md += `**Primary Diagnosis:** ${patient.condition?.primary_diagnosis || "Oncology"} (${patient.condition?.stage || "N/A"})  \n`;
  md += `**ECOG Performance Status:** ${patient.demographics?.ecog_ps ?? "N/A"}  \n\n`;
  
  md += `## Executive Summary\n`;
  const eligible = evaluations.filter(e => e.overall_eligibility === "ELIGIBLE");
  const potential = evaluations.filter(e => e.overall_eligibility === "POTENTIALLY_ELIGIBLE");
  const ineligible = evaluations.filter(e => e.overall_eligibility === "INELIGIBLE");
  
  md += `- **Total Protocol Documents Evaluated:** ${evaluations.length}\n`;
  md += `- **Directly Eligible:** ${eligible.length}\n`;
  md += `- **Potentially Eligible (Action Required):** ${potential.length}\n`;
  md += `- **Ineligible:** ${ineligible.length}\n\n`;

  md += `## Detailed Trial Adjudication Breakdown\n\n`;

  for (const ev of evaluations) {
    const icon = ev.overall_eligibility === "ELIGIBLE" ? "✅" : (ev.overall_eligibility === "POTENTIALLY_ELIGIBLE" ? "🟡" : "❌");
    md += `### ${icon} ${ev.trial_id}: ${ev.trial_title}\n`;
    md += `- **Phase / Indication:** ${ev.phase} | ${ev.condition}\n`;
    md += `- **Eligibility Status:** **${ev.overall_eligibility}**\n`;
    md += `- **Match Confidence:** ${ev.match_confidence}%\n`;
    md += `- **Clinical Review Rationale:** ${ev.executive_summary}\n\n`;

    if (ev.missing_information && ev.missing_information.length > 0) {
      md += `#### ⚠️ Missing Clinical Information / Diagnostic Actions Needed:\n`;
      for (const m of ev.missing_information) {
        md += `- ${m}\n`;
      }
      md += `\n`;
    }

    md += `#### Inclusion Criteria Evaluation:\n`;
    for (const inc of ev.evaluated_inclusions) {
      const stIcon = inc.status === "MET" ? "[MET]" : (inc.status === "UNMET" ? "[UNMET]" : "[MISSING]");
      md += `- **${stIcon} ${inc.id}:** ${inc.criterion}\n`;
      md += `  - *Evidence:* ${inc.evidence}\n`;
      md += `  - *Rationale:* ${inc.explanation}\n`;
      md += `  - *Citation:* ${inc.citation}\n`;
    }
    md += `\n`;

    md += `#### Exclusion Criteria Evaluation:\n`;
    for (const exc of ev.evaluated_exclusions) {
      const stIcon = exc.status === "MET" ? "[AVOIDED]" : (exc.status === "UNMET" ? "[TRIGGERED]" : "[UNKNOWN]");
      md += `- **${stIcon} ${exc.id}:** ${exc.criterion}\n`;
      md += `  - *Evidence:* ${exc.evidence}\n`;
      md += `  - *Rationale:* ${exc.explanation}\n`;
      md += `  - *Citation:* ${exc.citation}\n`;
    }
    md += `\n---\n\n`;
  }

  md += `\n*Notice: Report generated by Clinical Trial Eligibility Matcher GenAI Pipeline. Synthetic research data only. Intended for trial prescreening.*`;
  return md;
}

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
