import React, { useMemo } from "react";
import { PatientProfile, TrialEvaluation } from "../types";
import { generateMarkdownExport, downloadFile } from "../utils/reportExport";
import { Download, FileText, CheckCircle2, ArrowLeft, Printer } from "lucide-react";

interface Step5ExportProps {
  patient: PatientProfile;
  evaluations: TrialEvaluation[];
  onPrev: () => void;
}

export const Step5Export: React.FC<Step5ExportProps> = ({ patient, evaluations, onPrev }) => {
  // useMemo prevents rebuilding the report string on every parent re-render
  const mdContent = useMemo(
    () => generateMarkdownExport(patient, evaluations),
    [patient, evaluations]
  );

  const handleDownloadMarkdown = () => {
    downloadFile(
      mdContent,
      `clinical_trial_adjudication_${patient.id}.md`,
      "text/markdown"
    );
  };

  const handleDownloadHtml = () => {
    // Generate styled standalone HTML
    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Clinical Trial Eligibility Matcher - ${patient.id}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #1E293B; max-width: 850px; margin: 40px auto; padding: 0 20px; }
    h1, h2, h3 { color: #0B192C; }
    .badge { display: inline-block; padding: 3px 8px; border-radius: 4px; font-size: 12px; font-weight: bold; }
    .badge-eligible { background: #DCFCE7; color: #166534; }
    .badge-potential { background: #FEF3C7; color: #92400E; }
    .badge-ineligible { background: #FEE2E2; color: #991B1B; }
    .card { background: #FFFFFF; border: 1px solid #E2E8F0; border-radius: 8px; padding: 18px; margin-bottom: 20px; }
    .warning { background: #FFFBEB; border-left: 4px solid #F59E0B; padding: 12px 16px; margin: 12px 0; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
    th { background: #F1F5F9; text-align: left; padding: 8px; border-bottom: 2px solid #CBD5E1; }
    td { padding: 8px; border-bottom: 1px solid #E2E8F0; }
  </style>
</head>
<body>
  <h1>Clinical Trial Adjudication Report</h1>
  <p><strong>Patient Identifier:</strong> ${patient.id} (${patient.name}) | <strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
  <p><strong>Diagnosis:</strong> ${patient.condition.primary_diagnosis} (${patient.condition.stage}) | <strong>ECOG:</strong> ${patient.demographics.ecog_ps}</p>
  <hr>
  <h2>Evaluated Trials Summary</h2>
  ${evaluations.map(e => `
    <div class="card">
      <div style="display:flex; justify-content:space-between; align-items:center;">
        <h3>${e.trial_id}: ${e.trial_title}</h3>
        <span class="badge ${e.overall_eligibility === 'ELIGIBLE' ? 'badge-eligible' : (e.overall_eligibility === 'POTENTIALLY_ELIGIBLE' ? 'badge-potential' : 'badge-ineligible')}">
          ${e.overall_eligibility} (${e.match_confidence}% Match)
        </span>
      </div>
      <p><strong>Clinical Review Rationale:</strong> ${e.executive_summary}</p>
      ${e.missing_information && e.missing_information.length > 0 ? `
        <div class="warning">
          <strong>Missing Tests Required for Protocol Clearance:</strong>
          <ul>${e.missing_information.map(m => `<li>${m}</li>`).join('')}</ul>
        </div>
      ` : ''}
    </div>
  `).join('')}
  <footer style="margin-top: 40px; font-size: 12px; color: #64748B;">
    Generated by Clinical Trial Eligibility Matcher GenAI Pipeline. Synthetic research data.
  </footer>
</body>
</html>`;

    downloadFile(
      html,
      `clinical_trial_adjudication_${patient.id}.html`,
      "text/html"
    );
  };

  return (
    <div className="space-y-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-bold text-slate-900 m-0">Step 5: Export Clinical Adjudication Report</h2>
          <p className="text-sm text-slate-600 m-0 mt-1">
            Download comprehensive documentation formatted for clinical research coordinators, medical monitors, and PIs.
          </p>
        </div>

        <button
          onClick={onPrev}
          className="inline-flex items-center gap-1.5 bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 text-sm font-semibold px-3 py-2 rounded-lg transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span>Back to Results</span>
        </button>
      </div>

      {/* Download Action Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <button
          id="download-markdown-report-btn"
          onClick={handleDownloadMarkdown}
          className="flex items-start gap-4 p-5 rounded-xl border border-teal-200 bg-teal-50/50 hover:bg-teal-50 text-left transition-all group shadow-2xs hover:shadow-xs"
        >
          <div className="w-10 h-10 rounded-lg bg-teal-600 text-white flex items-center justify-center shrink-0 shadow-xs">
            <FileText className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2 font-bold text-sm text-slate-900">
              <span>Download Markdown Report</span>
              <Download className="w-4 h-4 text-teal-600 group-hover:translate-y-0.5 transition-transform" />
            </div>
            <p className="text-xs text-slate-600 mt-1 mb-0">
              Clean structured Markdown (.md) formatted with criteria citations, perfect for documentation notes and GitHub/GitLab clinical wikis.
            </p>
          </div>
        </button>

        <button
          id="download-html-report-btn"
          onClick={handleDownloadHtml}
          className="flex items-start gap-4 p-5 rounded-xl border border-slate-200 bg-white hover:bg-slate-50 text-left transition-all group shadow-2xs hover:shadow-xs"
        >
          <div className="w-10 h-10 rounded-lg bg-slate-900 text-white flex items-center justify-center shrink-0 shadow-xs">
            <Printer className="w-5 h-5" />
          </div>
          <div>
            <div className="flex items-center gap-2 font-bold text-sm text-slate-900">
              <span>Download Printable HTML Report</span>
              <Download className="w-4 h-4 text-slate-700 group-hover:translate-y-0.5 transition-transform" />
            </div>
            <p className="text-xs text-slate-600 mt-1 mb-0">
              Standalone responsive HTML with medical typography, print styles, and badges. Open in any browser or save as PDF.
            </p>
          </div>
        </button>
      </div>

      {/* Live Preview Box */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-2xs p-6 space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-slate-100">
          <div className="flex items-center gap-2 font-bold text-sm text-slate-900">
            <CheckCircle2 className="w-4 h-4 text-teal-600" />
            <span>Adjudication Report Preview</span>
          </div>
          <span className="text-xs text-slate-400 font-mono">clinical_trial_adjudication_{patient.id}.md</span>
        </div>

        <pre className="bg-slate-50 text-slate-800 p-4 rounded-lg font-mono text-xs overflow-x-auto border border-slate-200 whitespace-pre-wrap leading-relaxed max-h-96">
          {mdContent}
        </pre>
      </div>
    </div>
  );
};
